### ISSUE TITLE
new comments for @MichaelAlex86

### ISSUE THREAD

**Issue by MichaelAlex86** [MichaelAlex86/github-slideshow#3]
new comments for @MichaelAlex86

_Originally posted by @IgorFF76 in https://github.com/MichaelAlex86/github-slideshow/issues/1#issuecomment-759513274_

**Comment by IgorFF76** [comment]
ok. Thank you @MichaelAlex86

**Comment by MichaelAlex86** [comment]
#

**Comment by MichaelAlex86** [comment]
not end

**Comment by IgorFF76** [comment]
not end

**Comment by IgorFF76** [comment]
new txt
